<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>CSSFinal</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="CSSFinal_files/libs/clipboard/clipboard.min.js"></script>
<script src="CSSFinal_files/libs/quarto-html/quarto.js"></script>
<script src="CSSFinal_files/libs/quarto-html/popper.min.js"></script>
<script src="CSSFinal_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="CSSFinal_files/libs/quarto-html/anchor.min.js"></script>
<link href="CSSFinal_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="CSSFinal_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="CSSFinal_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="CSSFinal_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="CSSFinal_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">CSSFinal</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>Singapore is widely regarded as one of the world’s most well-connected cities, with a highly developed public transport system that serves a population of over 6.11 million residents. The country’s public transport infrastructure is frequently cited as a key contributor to its economic efficiency and high quality of life. However, despite this reputation, local discourse often highlights disparities in accessibility across neighbourhoods, with particular concern surrounding newer housing estates such as Tengah which are perceived to have weaker transport links to the rest of the island.</p>
<p>While recent transport investments have focused heavily on the expansion of the rail network (ie. the Mass Rapid Transit system) , bus services continue to play a crucial role in residents’ everyday commutes. This is especially important in an ageing society, where buses provide flexible, accessible transport options for residents who may be less able or willing to rely on rail-based travel. Bus routes also serve areas that are less densely populated or more peripheral, often described locally as “ulu,” where alternative transport options may be limited.</p>
<p>Against this backdrop, understanding the distribution of bus stops and their concentration across different roads offers valuable insight into patterns of accessibility and infrastructure provision within Singapore. By analysing publicly available bus stop data, this study explores how bus transport infrastructure is distributed across the city-state and examines whether connectivity appears evenly distributed or concentrated in specific areas.</p>
</section>
<section id="part-i-a-automated-data-collection" class="level1">
<h1>Part I-A Automated Data Collection</h1>
<p>This study aims to explore patterns of transport connectivity in Singapore through the distribution of bus stops and routes.</p>
<p>Following the automated data collection decision framework, Public transport data were identified as highly relevant, particularly information on bus stop locations and bus routes published by the Land Transport Authority (LTA) of Singapore.</p>
<p>The next step in the decision tree considers whether an application programming interface (API) exists that provides structured access to the relevant database. In this case, the LTA offers an official API through the LTA DataMall, which provides comprehensive access to many different types of public transport data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Load packages </span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pacman)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(httr, jsonlite, dplyr, ggplot2, purrr)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co">#Define base URL</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>base_url <span class="ot">&lt;-</span> <span class="st">"https://datamall2.mytransport.sg/ltaodataservice"</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co">#Define access tokens </span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>API_KEY <span class="ot">&lt;-</span> <span class="st">"aNXZQibBTGStKiyq3RGGiQ=="</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="co">#Correct endpoints</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>endpoint_busstop <span class="ot">&lt;-</span> <span class="st">"/BusStops"</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>endpoint_busroute <span class="ot">&lt;-</span> <span class="st">"/BusRoutes"</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="do">##For Bus Stops</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="co">#To get request </span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>get_busstops <span class="ot">&lt;-</span> <span class="cf">function</span>(skip) { </span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>  url <span class="ot">&lt;-</span> <span class="fu">paste0</span>(base_url, <span class="st">"/BusStops?$skip="</span>, skip) </span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>  response <span class="ot">&lt;-</span> <span class="fu">GET</span>( </span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>    url, </span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>    <span class="fu">add_headers</span>(<span class="at">AccountKey =</span> API_KEY, <span class="at">accept =</span> <span class="st">"application/json"</span>) ) </span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>  data <span class="ot">&lt;-</span> <span class="fu">content</span>(response, <span class="at">as =</span> <span class="st">"text"</span>, <span class="at">encoding =</span> <span class="st">"UTF-8"</span>) <span class="sc">%&gt;%</span> <span class="fu">fromJSON</span>(<span class="at">flatten =</span> <span class="cn">TRUE</span>) </span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(data<span class="sc">$</span>value) </span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>  } </span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a><span class="co">#Loop through pages (500 records per page) </span></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>all_busstops <span class="ot">&lt;-</span> <span class="fu">map_dfr</span>(<span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">60000</span>, <span class="at">by =</span> <span class="dv">500</span>), get_busstops) </span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a><span class="co">#Inspect results </span></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(all_busstops)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 5,195
Columns: 5
$ BusStopCode &lt;chr&gt; "01012", "01013", "01019", "01029", "01039", "01059", "011…
$ RoadName    &lt;chr&gt; "Victoria St", "Victoria St", "Victoria St", "Nth Bridge R…
$ Description &lt;chr&gt; "Hotel Grand Pacific", "St. Joseph's Ch", "Bras Basah Cplx…
$ Latitude    &lt;dbl&gt; 1.296848, 1.297710, 1.296990, 1.296673, 1.298208, 1.300757…
$ Longitude   &lt;dbl&gt; 103.8525, 103.8532, 103.8530, 103.8544, 103.8555, 103.8561…</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="do">##For Bus Routes </span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>get_busroutes <span class="ot">&lt;-</span> <span class="cf">function</span>(skip) { </span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  url <span class="ot">&lt;-</span> <span class="fu">paste0</span>(base_url, <span class="st">"/BusRoutes?$skip="</span>, skip) </span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  response <span class="ot">&lt;-</span> <span class="fu">GET</span>( </span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>    url, </span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">add_headers</span>(<span class="at">AccountKey =</span> API_KEY, <span class="at">accept =</span> <span class="st">"application/json"</span>) ) </span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  data <span class="ot">&lt;-</span> <span class="fu">content</span>(response, <span class="at">as =</span> <span class="st">"text"</span>, <span class="at">encoding =</span> <span class="st">"UTF-8"</span>) <span class="sc">%&gt;%</span> <span class="fu">fromJSON</span>(<span class="at">flatten =</span> <span class="cn">TRUE</span>) </span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(data<span class="sc">$</span>value) </span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>} </span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="co">#Loop through pages (500 records per page) </span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>all_busroutes <span class="ot">&lt;-</span> <span class="fu">map_dfr</span>(<span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">60000</span>, <span class="at">by =</span> <span class="dv">500</span>), get_busroutes) </span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a><span class="co">#Inspect results </span></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(all_busroutes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 26,538
Columns: 12
$ ServiceNo    &lt;chr&gt; "10", "10", "10", "10", "10", "10", "10", "10", "10", "10…
$ Operator     &lt;chr&gt; "SBST", "SBST", "SBST", "SBST", "SBST", "SBST", "SBST", "…
$ Direction    &lt;int&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, …
$ StopSequence &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17…
$ BusStopCode  &lt;chr&gt; "75009", "76059", "76069", "96289", "96109", "85079", "85…
$ Distance     &lt;dbl&gt; 0.0, 0.6, 1.1, 2.3, 2.7, 3.3, 3.5, 3.8, 4.1, 4.5, 4.8, 5.…
$ WD_FirstBus  &lt;chr&gt; "0500", "0502", "0504", "0508", "0509", "0511", "0511", "…
$ WD_LastBus   &lt;chr&gt; "2300", "2302", "2304", "2308", "2310", "2312", "2313", "…
$ SAT_FirstBus &lt;chr&gt; "0500", "0502", "0504", "0508", "0509", "0511", "0512", "…
$ SAT_LastBus  &lt;chr&gt; "2300", "2301", "2301", "2303", "2304", "2306", "2306", "…
$ SUN_FirstBus &lt;chr&gt; "0500", "0502", "0503", "0507", "0508", "0510", "0511", "…
$ SUN_LastBus  &lt;chr&gt; "2300", "2302", "2304", "2308", "2309", "2311", "2312", "…</code></pre>
</div>
</div>
<p>Each data set was cleaned and tidied prior to merging. The merge enables the integration of complementary information, geographic coordinates from the bus stop data and route structure details from the bus route data, producing a refined data set suitable for deeper analysis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Data frame </span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>all_busstops  <span class="ot">&lt;-</span> dplyr<span class="sc">::</span><span class="fu">bind_rows</span>(all_busstops)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>all_busroutes <span class="ot">&lt;-</span> dplyr<span class="sc">::</span><span class="fu">bind_rows</span>(all_busroutes)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(all_busstops)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "data.frame"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(all_busroutes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "data.frame"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Cleaning data for bus stops</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>bus_stops_clean <span class="ot">&lt;-</span> all_busstops <span class="sc">%&gt;%</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">BusStopCode =</span> <span class="fu">as.character</span>(BusStopCode),</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">RoadName =</span> <span class="fu">as.character</span>(RoadName),</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">Description =</span> <span class="fu">as.character</span>(Description),</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">Latitude =</span> <span class="fu">as.numeric</span>(Latitude),</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">Longitude =</span> <span class="fu">as.numeric</span>(Longitude)</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>() <span class="sc">%&gt;%</span></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Latitude), <span class="sc">!</span><span class="fu">is.na</span>(Longitude))</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a><span class="co">#Cleaning data for bus routes</span></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>bus_routes_clean <span class="ot">&lt;-</span> all_busroutes <span class="sc">%&gt;%</span></span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">ServiceNo =</span> <span class="fu">as.character</span>(ServiceNo),</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">Operator =</span> <span class="fu">as.character</span>(Operator),</span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">Direction =</span> <span class="fu">as.integer</span>(Direction),</span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">StopSequence =</span> <span class="fu">as.integer</span>(StopSequence),</span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">BusStopCode  =</span> <span class="fu">as.character</span>(BusStopCode),</span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">Distance =</span> <span class="fu">as.numeric</span>(Distance)</span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>()</span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-25"><a href="#cb9-25" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(bus_stops_clean)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 5,195
Columns: 5
$ BusStopCode &lt;chr&gt; "01012", "01013", "01019", "01029", "01039", "01059", "011…
$ RoadName    &lt;chr&gt; "Victoria St", "Victoria St", "Victoria St", "Nth Bridge R…
$ Description &lt;chr&gt; "Hotel Grand Pacific", "St. Joseph's Ch", "Bras Basah Cplx…
$ Latitude    &lt;dbl&gt; 1.296848, 1.297710, 1.296990, 1.296673, 1.298208, 1.300757…
$ Longitude   &lt;dbl&gt; 103.8525, 103.8532, 103.8530, 103.8544, 103.8555, 103.8561…</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(bus_routes_clean)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 26,538
Columns: 12
$ ServiceNo    &lt;chr&gt; "10", "10", "10", "10", "10", "10", "10", "10", "10", "10…
$ Operator     &lt;chr&gt; "SBST", "SBST", "SBST", "SBST", "SBST", "SBST", "SBST", "…
$ Direction    &lt;int&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, …
$ StopSequence &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17…
$ BusStopCode  &lt;chr&gt; "75009", "76059", "76069", "96289", "96109", "85079", "85…
$ Distance     &lt;dbl&gt; 0.0, 0.6, 1.1, 2.3, 2.7, 3.3, 3.5, 3.8, 4.1, 4.5, 4.8, 5.…
$ WD_FirstBus  &lt;chr&gt; "0500", "0502", "0504", "0508", "0509", "0511", "0511", "…
$ WD_LastBus   &lt;chr&gt; "2300", "2302", "2304", "2308", "2310", "2312", "2313", "…
$ SAT_FirstBus &lt;chr&gt; "0500", "0502", "0504", "0508", "0509", "0511", "0512", "…
$ SAT_LastBus  &lt;chr&gt; "2300", "2301", "2301", "2303", "2304", "2306", "2306", "…
$ SUN_FirstBus &lt;chr&gt; "0500", "0502", "0503", "0507", "0508", "0510", "0511", "…
$ SUN_LastBus  &lt;chr&gt; "2300", "2302", "2304", "2308", "2309", "2311", "2312", "…</code></pre>
</div>
</div>
<p>Due to the nature of the data, there were no missing variables. The two data sets were merged using the bus stop code variable, which is a unique number given to each bus stop.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co">#To merge data sets </span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>routes_with_locations <span class="ot">&lt;-</span> <span class="fu">merge</span>(</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  bus_routes_clean,</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  bus_stops_clean,</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">by =</span> <span class="st">"BusStopCode"</span>,</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">all =</span> <span class="cn">FALSE</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Save the refined data set for use in Shiny application.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Create a data folder</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dir.create</span>(<span class="st">"data"</span>, <span class="at">showWarnings =</span> <span class="cn">FALSE</span>)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Save the data set</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="fu">saveRDS</span>(routes_with_locations, <span class="st">"data/routes_with_locations.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="part-i-b-data-exploration-and-contextualisation" class="level1">
<h1>Part I-B Data Exploration and Contextualisation</h1>
<p>The refined data set comprises two data sets: bus routes and bus stops, each offering distinct but complementary insights into Singapore’s public transport infrastructure. The bus routes dataset contains 26,538 observations across 12 variables, while the bus stops dataset includes 5,195 observations across 5 variables. In the bus routes data, each row represents a unique bus stop along a service route, with variables detailing the service route number (identifying the bus), operator (i.e., SBS Transit or Go-Ahead Singapore), the direction of the service, the sequence of the stop in the route, the bus stop code, the distance from the first stop of the route, and first and last bus timings for weekdays, Saturdays, and Sundays. The bus stops data set provides spatial and descriptive context for each stop, including the bus stop code, road name, description, longitude, and latitude.</p>
<p>This data source was selected for its rich potential in exploring questions of urban accessibility, equity, and infrastructure planning which are core concerns in the social sciences as it affects people’s quality of life. By looking at these service routes and the spatial distribution of the bus stops, researchers can examine how transport connectivity varies across neighborhoods, which areas are underserved, and how public transit aligns with broader goals like social inclusion, access to job opportunities, and environmental sustainability.</p>
</section>
<section id="part-ii-a-building-an-interactive-dashboard-with-r-shiny" class="level1">
<h1>Part II-A Building an Interactive Dashboard with R Shiny</h1>
<p>The interactive dashboard was designed to provide a multifaceted view of bus stop connectivity in Singapore, using the refined data set of bus routes and bus stops. Three visualisations were implemented in the Shiny dashboard to highlight different dimensions of connectivity.</p>
<section id="visualisation-1-interactive-map" class="level3">
<h3 class="anchored" data-anchor-id="visualisation-1-interactive-map">Visualisation 1 (Interactive Map)</h3>
<p>The interactive map plots each bus stop geographically, with bubble sizes proportional to the number of bus services available. Hence, the larger the bubble the more bus services available at that particular stop. Therefore, larger bubbles immediately signal highly connected stops, while smaller ones highlight areas with lower accessibility. This spatial representation makes disparities in public transport provision visible at a glance: dense clusters of large bubbles appear around central economic and tourism hubs such as the Central Business District, whereas smaller bubbles dominate more peripheral regions. The map also raises important social questions. In a city where a lack of housing has long been a problem, proximity to well‑connected train stations and bus stops is a crucial factor that shapes residents’ quality of life as it affects commute times and cost. At the same time, the map illustrates the foresight of Singapore’s urban planning. Even in the “outskirts,” major bus interchanges are strategically distributed across the island, ensuring that connectivity is not confined to the just the Central Business District but is spread through regional hubs. Nonetheless, the map reveals pockets of relative under‑service, such as Bukit Timah and Tengah, where bus accessibility remains limited. The map was chosen because spatial representation is both intuitive and powerful, enabling users to connect service density with geography and to identify underserved regions that warrant closer policy attention.</p>
</section>
<section id="visualisation-2-connectivity-categories-bar-chart" class="level3">
<h3 class="anchored" data-anchor-id="visualisation-2-connectivity-categories-bar-chart">Visualisation 2 (Connectivity categories bar chart)</h3>
<p><img src="images/Screenshot%202026-01-19%20at%2011.46.46%20AM.png" class="img-fluid"></p>
<p>The connectivity categories bar chart provides a structural overview of the bus network by grouping stops into three categories: ‘Local’, ‘Connector’, and ‘Hub’. These categories are defined by service count thresholds, which the user can adjust interactively via a slider toggle in the dashboard. This feature allows users to explore how different definitions of connectivity affect the overall distribution. In my configuration, stops with up to 2 services are classified as ‘Local’, those with 3 to 5 as ‘Connectors’, and anything above 5 as ‘Hubs’. The output reveals that 1,894 stops fall into the ‘Local’ category, 1,492 are ‘Connectors’, and 1,809 are ‘Hubs’. This distribution suggests a relatively even spread between lightly connected stops and major hubs, with ‘Connectors’ forming the smallest group. The high number of ‘Local’ stops suggests broad geographic coverage which is supported by the map in visualisation 1. Moreover, the near‑equal number of Hubs indicates that connectivity may be concentrated in key locations, reinforcing a degree of centralisation. At the same time, this pattern suggests that many commuters are close enough to major stops where multiple services converge, making it easier to catch a bus to one destination and then transfer to another. In practice, this means that people are not only connected to their immediate neighbourhoods but also have access to a wider network of travel options, such as trains, supporting flexibility and mobility across the island. The bar chart was chosen because it allows us to understand this complex relationship in an easier form, enabling meaningful discussion surrounding equity, efficiency, and the broader social implications of urban planning.</p>
</section>
<section id="visualisation-3-ridgeline-graph" class="level3">
<h3 class="anchored" data-anchor-id="visualisation-3-ridgeline-graph">Visualisation 3 (Ridgeline graph)</h3>
<p>The ridgeline plot illustrates the distribution of bus service counts across selected roads, offering a nuanced view of how connectivity varies within the network. Each curve represents a road, with its shape showing the density of bus stops by number of services. Roads whose curves are shifted to the right host better‑connected stops, while those with peaks near the left are dominated by low‑service stops. Rather than plotting every road, which would overwhelm the visual, I designed the dashboard to let users choose which roads they want to compare. This makes the plot more focused and interpretable, while also allowing users to explore areas relevant to their own experience.</p>
<p>For my analysis, I selected Orchard Road, Jurong West Street 91, and Tengah Boulevard. Orchard Road was chosen for its centrality and dense transport infrastructure, it’s curve shows multiple peaks extending up to 40 services, reflecting high accessibility to public buses. Jurong West Street 91 was a personal choice, as I grew up on that street and often experienced long commutes to town, typically requiring a bus‑to‑train transfer. Its curve peaks sharply around 0 to 5 services, confirming the limited direct bus connectivity I experienced. Tengah was included because of recent public complaints about poor transport access in the newly developed area. Interestingly, its curve peaks around 10 services, which is way more than Jurong West which is an arguably more “mature” estate. Suggesting that while some stops are moderately connected, the overall distribution remains narrow in comparison to places like Orchard Road.</p>
<p>The ridgeline plot was chosen because it exposes these contrasts, showing not just how many services exist, but how they are distributed across space.</p>
</section>
</section>
<section id="part-ii-c-critical-engagement-with-ai-copilot" class="level1">
<h1>Part II-C Critical Engagement with AI: Copilot</h1>
<p>Copilot’s contributions were most evident in several key moments. When my <code>mutate</code> call failed, Copilot suggested using <code>dplyr::bind_rows()</code> to combine data frames, which provided a practical workaround and helped me progress in my work.</p>
<p>It also guided me in choosing between file formats. While I initially preferred CSV for familiarity, Copilot recommended <code>.rds</code> to preserve R objects more faithfully. This advice pushed me beyond my comfort zone and allowed me to learn a new data format which was interesting to work with. It also helps to improve reproducibility, especially once I understood the differences between the two.</p>
<p>I was also having trouble regarding the app not loading due to R being unable to find the data set. Copilot’s explanation of <code>../data/routes_with_locations.rds</code> and the meaning of <code>..</code> as “go up one directory” was particularly insightful, as it allowed me to progress in my work and learn a new phrase in regards to file management.</p>
<p>Another valuable intervention came in the design of my dashboard. My ridgeline plot was initially too cramped because it attempted to display every road at once. The reactive filter was the part Copilot suggested.</p>
<div class="cell">
<pre class="df cell-code"><code></code></pre>
</div>
<p>Copilot suggested restructuring the app so that users could select the roads they wanted to analyse. These refinements improved usability and readability, demonstrating Copilot’s strength in offering innovative problem‑solving approaches that enhanced the user experience.</p>
<p>Beyond code refinement, Copilot shaped my learning experience and confidence. While its suggestions were sometimes generic, they prompted me to think about how AI cannot replace the human aspect of the social sciences. While Copilot can refine code and suggest technical fixes, it cannot interpret lived experiences, contextual inequalities, or the values embedded in urban planning. Those dimensions require human judgment, empathy, and critical reflection.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>
